# The MIT License (MIT)
# Copyright © 2016 Michał Dobaczewski <mdobak@gmail.com>

source src/config.sh
source src/util.sh
source src/hosts.sh

source test/functions_stubs.sh

load helpers

CRESET=""
CRED=""
CORANGE=""
CYELLOW=""
CBLUE=""
CLBLUE=""

export PATH="$BATS_TEST_DIRNAME/stub:$BATS_TEST_DIRNAME/tmpstub:$PATH"

@test "test bulding hosts file" {
  run hosts_build_file

  assert_output "172.17.0.1 registry # Generated by docker-dev-env\n172.17.0.2 example-mysql # Generated by docker-dev-env\n172.17.0.3 foobar1.local # Generated by docker-dev-env\n172.17.0.4 foobar2.local # Generated by docker-dev-env\n172.17.0.5 dnsmasq-server # Generated by docker-dev-env\n"
}
