# The MIT License (MIT)
# Copyright © 2016 Michał Dobaczewski <mdobak@gmail.com>

source src/config.sh
source src/util.sh
source src/nfs.sh

source test/functions_stubs.sh

load helpers

CRESET=""
CRED=""
CORANGE=""
CYELLOW=""
CBLUE=""
CLBLUE=""

export PATH="$BATS_TEST_DIRNAME/stub:$BATS_TEST_DIRNAME/tmpstub:$PATH"

@test "test generating /etc/exports" {
  stub nfsd ""

  echo '' > "$BATS_TMPDIR/exports"
  run nfs_setup_nfsd_on_host test /mnt/Volumes "-alldirs -maproot=0" "$BATS_TMPDIR/exports"
  OUTPUT=$(cat "$BATS_TMPDIR/exports")

  OUTPUT="${OUTPUT#"${OUTPUT%%[![:space:]]*}"}"
  OUTPUT="${OUTPUT%"${OUTPUT##*[![:space:]]}"}"

  assert_equal "# Generated by docker-dev-env
/mnt/Volumes 192.168.99.100 -alldirs -maproot=0" "$OUTPUT"
}

@test "test removing old rules from /etc/exports" {
  stub nfsd ""

  echo -e "# Generated by docker-dev-env\n/mnt/Volumes 10.0.0.1 -alldirs -maproot=0" > "$BATS_TMPDIR/exports"
  run nfs_setup_nfsd_on_host test /mnt/Volumes "-alldirs -maproot=0" "$BATS_TMPDIR/exports"
  OUTPUT=$(cat "$BATS_TMPDIR/exports")

  OUTPUT="${OUTPUT#"${OUTPUT%%[![:space:]]*}"}"
  OUTPUT="${OUTPUT%"${OUTPUT##*[![:space:]]}"}"

  assert_equal "# Generated by docker-dev-env
/mnt/Volumes 192.168.99.100 -alldirs -maproot=0" "$OUTPUT"
}

@test "test keeping rules in /etc/exports" {
  stub nfsd ""

  echo -e "/mnt/NotDockerExport 10.0.0.1 -alldirs -maproot=0" > "$BATS_TMPDIR/exports"
  run nfs_setup_nfsd_on_host test /mnt/Volumes "-alldirs -maproot=0" "$BATS_TMPDIR/exports"
  OUTPUT=$(cat "$BATS_TMPDIR/exports")

  OUTPUT="${OUTPUT#"${OUTPUT%%[![:space:]]*}"}"
  OUTPUT="${OUTPUT%"${OUTPUT##*[![:space:]]}"}"

  assert_equal "/mnt/NotDockerExport 10.0.0.1 -alldirs -maproot=0
# Generated by docker-dev-env
/mnt/Volumes 192.168.99.100 -alldirs -maproot=0" "$OUTPUT"
}
