#!/bin/bash
#
# The MIT License (MIT)
# Copyright © 2016 Michał Dobaczewski <mdobak@gmail.com>
#
# Based on the docker-machine-nfs script written by Toni Van de Voorde:
# https://github.com/adlogix/docker-machine-nfs
#

_NFS_SH=1

# Checks if the NFS shared folder is already mounted on the Docker Machine.
#
# $1 - The Docker Machie name.
# $2 - Path to the mount directory to check.
nfs_is_mounted ()
{
  local DOCKER_MACHINE_NAME=$1
  local MOUNT_DIR=$2
  local HOST_IP=$(dm_host_ip $DOCKER_MACHINE_NAME)

  if run_as_user docker-machine ssh $DOCKER_MACHINE_NAME sudo df | grep -q "$HOST_IP:$MOUNT_DIR"; then
    return $true
  else
    return $false
  fi
}

# Configures the NFSD on Mac OS.
#
# $1 - The Docker Machie name.
# $2 - Path to the mount directory.
# $3 - NFS exports options for specifed directory. By default "-alldirs -maproot=0".
nfs_setup_nfsd_on_host ()
{
  local DOCKER_MACHINE_NAME=$1
  local MOUNT_DIR=$2
  local NFS_CONFIG=$3;
  local IP=$(run_as_user docker-machine ip $DOCKER_MACHINE_NAME)

  if [[ -z $NFS_CONFIG ]]; then
    NFS_CONFIG="-alldirs -maproot=0"
  fi

  sed -i .bak "/# Generated by docker-dev-env/{N;d;}" /etc/exports
  printf "\n# Generated by docker-dev-env\n$MOUNT_DIR $IP $NFS_CONFIG\n" >> /etc/exports

  err_catch nfsd restart
  err_catch nfsd checkexports
}

# Mounts NFS shares on the Docker Machine.
#
# $1 - The Docker Machie name.
# $2 - Path to the mount directory.
# $3 - Mount opitions on the Docker Machine. By default "moacl,async".
nfs_setup_on_docker_machine ()
{
  local DOCKER_MACHINE_NAME=$1
  local MOUNT_DIR=$2
  local MOUNT_OPTIONS=$3;
  local HOST_IP=$(dm_host_ip $DOCKER_MACHINE_NAME)

  if [[ -z $MOUNT_OPTIONS ]]; then
    MOUNT_OPTIONS="nolock,noacl,async"
  fi

  local BOOTLOCAL_FILE='#/bin/bash
sudo umount /Users
sudo mkdir -p '$MOUNT_DIR'
sudo /usr/local/etc/init.d/nfs-client start
sudo mount -t nfs -o '$MOUNT_OPTIONS' '$HOST_IP':'$MOUNT_DIR' '$MOUNT_DIR

  run_as_user docker-machine ssh $DOCKER_MACHINE_NAME \
    "echo '$BOOTLOCAL_FILE' | sudo tee /var/lib/boot2docker/bootlocal.sh && sudo chmod +x /var/lib/boot2docker/bootlocal.sh" \
    > /dev/null

  if ! nfs_is_mounted $DOCKER_MACHINE_NAME $MOUNT_DIR; then
    dm_restart $DOCKER_MACHINE_NAME
  fi

  if ! nfs_is_mounted $DOCKER_MACHINE_NAME $MOUNT_DIR; then
    return $false
  fi

  return $true;
}
